package com.xyehyin.hexuanning.config.seed;

import com.xyehyin.hexuanning.constant.PermissionConstants;
import com.xyehyin.hexuanning.entity.Permission;

import java.util.HashSet;
import java.util.List;

public record PermissionSeed(String code, String name) {
    public Permission toEntity() {
        return new Permission(null, code, name, new HashSet<>());
    }

    public static List<PermissionSeed> defaults() {
        return List.of(
                new PermissionSeed(PermissionConstants.DASHBOARD, "仪表盘"),
                new PermissionSeed(PermissionConstants.USER_LIST_ALL, "查看所有用户列表"),
                new PermissionSeed(PermissionConstants.USER_VIEW_ALL, "查看任意用户详情"),
                new PermissionSeed(PermissionConstants.USER_VIEW_SELF, "查看自己的信息"),
                new PermissionSeed(PermissionConstants.USER_CREATE_ALL, "创建用户"),
                new PermissionSeed(PermissionConstants.USER_EDIT_ALL, "编辑用户"),
                new PermissionSeed(PermissionConstants.USER_EDIT_SELF, "编辑自己的信息"),
                new PermissionSeed(PermissionConstants.USER_DELETE_ALL, "删除用户"),
                new PermissionSeed(PermissionConstants.USER_UPDATE_STATUS, "修改用户状态"),
                new PermissionSeed(PermissionConstants.USER_UPDATE_PASSWORD_ALL, "修改任意用户密码"),
                new PermissionSeed(PermissionConstants.USER_UPDATE_PASSWORD_SELF, "修改自己密码"),
                new PermissionSeed(PermissionConstants.USER_UPDATE_ROLE, "修改用户角色"),
                new PermissionSeed(PermissionConstants.ROLE_LIST_ALL, "查看角色列表"),
                new PermissionSeed(PermissionConstants.ROLE_VIEW_ALL, "查看角色详情"),
                new PermissionSeed(PermissionConstants.ROLE_CREATE_ALL, "新增角色"),
                new PermissionSeed(PermissionConstants.ROLE_EDIT_ALL, "编辑角色"),
                new PermissionSeed(PermissionConstants.ROLE_DELETE_ALL, "删除角色"),
                new PermissionSeed(PermissionConstants.ROLE_ASSIGN_ALL, "分配角色权限"),
                new PermissionSeed(PermissionConstants.PERMISSION_LIST_ALL, "查看权限列表"),
                new PermissionSeed(PermissionConstants.PERMISSION_VIEW_ALL, "查看权限详情"),
                new PermissionSeed(PermissionConstants.PERMISSION_CREATE_ALL, "新增权限"),
                new PermissionSeed(PermissionConstants.PERMISSION_EDIT_ALL, "编辑权限"),
                new PermissionSeed(PermissionConstants.PERMISSION_DELETE_ALL, "删除权限"),
                new PermissionSeed(PermissionConstants.COURSE_LIST_ALL, "查看所有课程"),
                new PermissionSeed(PermissionConstants.COURSE_LIST_SELF, "查看自己的课程"),
                new PermissionSeed(PermissionConstants.COURSE_VIEW_ALL, "查看任意课程详情"),
                new PermissionSeed(PermissionConstants.COURSE_VIEW_SELF, "查看自己的课程详情"),
                new PermissionSeed(PermissionConstants.COURSE_CREATE_ALL, "创建任意课程"),
                new PermissionSeed(PermissionConstants.COURSE_CREATE_SELF, "创建自己的课程"),
                new PermissionSeed(PermissionConstants.COURSE_EDIT_ALL, "编辑任意课程"),
                new PermissionSeed(PermissionConstants.COURSE_EDIT_SELF, "编辑自己的课程"),
                new PermissionSeed(PermissionConstants.COURSE_DELETE_ALL, "删除任意课程"),
                new PermissionSeed(PermissionConstants.COURSE_DELETE_SELF, "删除自己的课程"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_LIST_ALL, "查看所有知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_LIST_SELF, "查看自己的知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_VIEW_ALL, "查看任意知识点详情"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_VIEW_SELF, "查看自己的知识点详情"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_CREATE_ALL, "创建任意知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_CREATE_SELF, "创建自己的知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_EDIT_ALL, "编辑任意知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_EDIT_SELF, "编辑自己的知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_DELETE_ALL, "删除任意知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_DELETE_SELF, "删除自己的知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_IMPORT, "导入知识点"),
                new PermissionSeed(PermissionConstants.KNOWLEDGE_POINT_EXPORT, "导出知识点"),
                new PermissionSeed(PermissionConstants.QUESTION_LIST_ALL, "查看所有题目"),
                new PermissionSeed(PermissionConstants.QUESTION_LIST_SELF, "查看自己的题目"),
                new PermissionSeed(PermissionConstants.QUESTION_VIEW_ALL, "查看任意题目详情"),
                new PermissionSeed(PermissionConstants.QUESTION_VIEW_SELF, "查看自己的题目详情"),
                new PermissionSeed(PermissionConstants.QUESTION_CREATE_ALL, "创建任意题目"),
                new PermissionSeed(PermissionConstants.QUESTION_CREATE_SELF, "创建自己的题目"),
                new PermissionSeed(PermissionConstants.QUESTION_EDIT_ALL, "编辑任意题目"),
                new PermissionSeed(PermissionConstants.QUESTION_EDIT_SELF, "编辑自己的题目"),
                new PermissionSeed(PermissionConstants.QUESTION_DELETE_ALL, "删除任意题目"),
                new PermissionSeed(PermissionConstants.QUESTION_DELETE_SELF, "删除自己的题目"),
                new PermissionSeed(PermissionConstants.QUESTION_IMPORT, "导入题目"),
                new PermissionSeed(PermissionConstants.QUESTION_EXPORT, "导出题目"),
                new PermissionSeed(PermissionConstants.AI_GENERATE_QUESTION, "AI生成题目"),
                new PermissionSeed(PermissionConstants.AI_CONFIG_MANAGE, "AI配置管理"),
                new PermissionSeed(PermissionConstants.FILE_UPLOAD, "上传文件"),
                new PermissionSeed(PermissionConstants.FILE_DELETE, "删除文件"),
                new PermissionSeed(PermissionConstants.FILE_VIEW, "查看文件"),
                new PermissionSeed(PermissionConstants.STATISTICS_COURSE, "课程统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_QUESTION, "题目统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_EXERCISE, "练习统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_USER, "用户统计"),
                new PermissionSeed(PermissionConstants.CATEGORY_LIST_ALL, "查看分类列表"),
                new PermissionSeed(PermissionConstants.CATEGORY_VIEW_ALL, "查看分类详情"),
                new PermissionSeed(PermissionConstants.CATEGORY_CREATE_ALL, "新增分类"),
                new PermissionSeed(PermissionConstants.CATEGORY_EDIT_ALL, "编辑分类"),
                new PermissionSeed(PermissionConstants.CATEGORY_DELETE_ALL, "删除分类"),
                new PermissionSeed(PermissionConstants.PAPER_LIST_PUBLIC, "学生查看公开试卷"),
                new PermissionSeed(PermissionConstants.PAPER_VIEW_PUBLIC, "学生查看公开试卷详情"),
                new PermissionSeed(PermissionConstants.PAPER_LIST_SELF, "教师查看自己创建的试卷"),
                new PermissionSeed(PermissionConstants.PAPER_VIEW_SELF, "教师查看自己创建的试卷详情"),
                new PermissionSeed(PermissionConstants.PAPER_CREATE, "教师创建试卷"),
                new PermissionSeed(PermissionConstants.PAPER_EDIT_SELF, "教师编辑自己创建的试卷"),
                new PermissionSeed(PermissionConstants.PAPER_DELETE_SELF, "教师删除自己创建的试卷"),
                new PermissionSeed(PermissionConstants.PAPER_PUBLISH_SELF, "教师发布自己创建的试卷"),
                new PermissionSeed(PermissionConstants.PAPER_ARCHIVE_SELF, "教师归档自己创建的试卷"),
                new PermissionSeed(PermissionConstants.PAPER_LIST_ALL, "管理员查看所有试卷"),
                new PermissionSeed(PermissionConstants.PAPER_VIEW_ALL, "管理员查看所有试卷详情"),
                new PermissionSeed(PermissionConstants.PAPER_EDIT_ALL, "管理员编辑所有试卷"),
                new PermissionSeed(PermissionConstants.PAPER_DELETE_ALL, "管理员删除所有试卷"),
                new PermissionSeed(PermissionConstants.PAPER_PUBLISH_ALL, "管理员发布所有试卷"),
                new PermissionSeed(PermissionConstants.PAPER_ARCHIVE_ALL, "管理员归档所有试卷"),
                new PermissionSeed(PermissionConstants.PAPER_MANAGE_QUESTIONS, "管理试卷题目"),
                new PermissionSeed(PermissionConstants.PAPER_QUESTION_ADD, "添加题目到试卷"),
                new PermissionSeed(PermissionConstants.PAPER_QUESTION_REMOVE, "从试卷移除题目"),
                new PermissionSeed(PermissionConstants.PAPER_QUESTION_REORDER, "调整试卷题目顺序"),
                new PermissionSeed(PermissionConstants.PAPER_QUESTION_SCORE, "设置试卷题目分值"),
                new PermissionSeed(PermissionConstants.GRADING_AUTO, "自动判分"),
                new PermissionSeed(PermissionConstants.GRADING_AI, "AI判分"),
                new PermissionSeed(PermissionConstants.GRADING_MANUAL, "手动判分"),
                new PermissionSeed(PermissionConstants.GRADING_VIEW, "查看判分结果"),
                new PermissionSeed(PermissionConstants.GRADING_REVIEW_LIST, "查看待批改题目列表"),
                new PermissionSeed(PermissionConstants.STATISTICS_PAPER_VIEW, "查看试卷统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_QUESTION_VIEW, "查看题目统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_STUDENT_VIEW, "查看学生统计"),
                new PermissionSeed(PermissionConstants.STATISTICS_OVERVIEW_VIEW, "查看统计概览"),
                new PermissionSeed(PermissionConstants.PRACTICE_START, "开始练习"),
                new PermissionSeed(PermissionConstants.PRACTICE_SUBMIT, "提交练习"),
                new PermissionSeed(PermissionConstants.PRACTICE_LIST_SELF, "获取所有可用试卷"),
                new PermissionSeed(PermissionConstants.PRACTICE_VIEW_SELF, "查看自己的练习会话"),
                new PermissionSeed(PermissionConstants.PRACTICE_RECORD_LIST_SELF, "列出自己的练习记录"),
                new PermissionSeed(PermissionConstants.PRACTICE_RECORD_LIST_ALL, "列出所有的练习记录"),
                new PermissionSeed(PermissionConstants.PRACTICE_RESULT_VIEW_SELF, "查看自己的练习结果"),
                new PermissionSeed(PermissionConstants.PRACTICE_RESULT_VIEW_ALL, "查看所有的练习结果"),
                new PermissionSeed(PermissionConstants.PRACTICE_MARK, "题目标记"),
                new PermissionSeed(PermissionConstants.PRACTICE_OVERVIEW_SELF, "查看自己的练习进度概览"),
                new PermissionSeed(PermissionConstants.PRACTICE_HISTORY_SELF, "查看自己的练习历史"),
                new PermissionSeed(PermissionConstants.PRACTICE_STATISTICS_SELF, "查看自己的练习统计"),
                new PermissionSeed(PermissionConstants.PRACTICE_DETAIL_SELF, "查看自己的练习题目详情")
        );
    }
}